name: PrisonMines
version: "${version}"
main: tech.mcprison.prison.mines.plugins.MinesSpigot
depend: [Prison]
description: A ranks module for Prison.
author: The MC-Prison Team
website: https://mc-prison.tech